image: alpine

docs:
  script:
  - cd docs/
  - doxygen Doxyfile
  - cd ../
  - cp -r /srv/www/htdocs/docs.brainhub.co/sdk/html/* /srv/www/htdocs/docs.brainhub.co/sdk/backup/*
  - mv docs/out/html/* /srv/www/htdocs/docs.brainhub.co/sdk/html/
  artifacts:
    paths:
    - public
# only:
# - master
